.build_dev:
  image: google/cloud-sdk:330.0.0-slim
  services:
    - docker:19.03.13-dind
#    - docker:20-dind
#    - docker:20.10-dind
#    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  before_script:
    - PROJECT_ID=$(gcloud config list project --format="value(core.project)")
    - echo $SERVICE_ACCOUNT_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud auth configure-docker
    - COVERAGE=0
    - docker version
#    - docker info
  script:
    - make build
    - make run
    - make pytest
    - COVERAGE=$(grep -E '<span class="pc_cov">([0-9]{1,3})%</span>' app/htmlcov/index.html | grep -o '[[:digit:]]*')
    - echo "COVERAGE ${COVERAGE}"
    - mv app/htmlcov/ public
    - if [ $COVERAGE -lt 80 ]; then exit 1 ;fi
    - make push
#  artifacts:
#    reports:
#      cobertura: app/coverage.xml
  artifacts:
    paths:
#      - app/htmlcov
      - public
